<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit14d3949c80515e2038faf0d0775e29d3
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('GiftFlow\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \GiftFlow\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit14d3949c80515e2038faf0d0775e29d3', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \GiftFlow\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit14d3949c80515e2038faf0d0775e29d3', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\GiftFlow\Vendor\Composer\Autoload\ComposerStaticInit14d3949c80515e2038faf0d0775e29d3::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
