<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit6c14230471ff6ac7e984c7b96310f27a
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('GiftFlow\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \GiftFlow\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit6c14230471ff6ac7e984c7b96310f27a', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \GiftFlow\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit6c14230471ff6ac7e984c7b96310f27a', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\GiftFlow\Vendor\Composer\Autoload\ComposerStaticInit6c14230471ff6ac7e984c7b96310f27a::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
