<?php

namespace GiftFlow\Vendor\Stripe\Util;

class ObjectTypes
{
    /**
     * @var array Mapping from object types to resource classes
     */
    const mapping
        = [
            \GiftFlow\Vendor\Stripe\Collection::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Collection::class,
            \GiftFlow\Vendor\Stripe\Issuing\CardDetails::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Issuing\CardDetails::class,
            \GiftFlow\Vendor\Stripe\SearchResult::OBJECT_NAME => \GiftFlow\Vendor\Stripe\SearchResult::class,
            \GiftFlow\Vendor\Stripe\File::OBJECT_NAME_ALT => \GiftFlow\Vendor\Stripe\File::class,
            // object classes: The beginning of the section generated from our OpenAPI spec
            \GiftFlow\Vendor\Stripe\Account::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Account::class,
            \GiftFlow\Vendor\Stripe\AccountLink::OBJECT_NAME => \GiftFlow\Vendor\Stripe\AccountLink::class,
            \GiftFlow\Vendor\Stripe\AccountSession::OBJECT_NAME => \GiftFlow\Vendor\Stripe\AccountSession::class,
            \GiftFlow\Vendor\Stripe\ApplePayDomain::OBJECT_NAME => \GiftFlow\Vendor\Stripe\ApplePayDomain::class,
            \GiftFlow\Vendor\Stripe\Application::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Application::class,
            \GiftFlow\Vendor\Stripe\ApplicationFee::OBJECT_NAME => \GiftFlow\Vendor\Stripe\ApplicationFee::class,
            \GiftFlow\Vendor\Stripe\ApplicationFeeRefund::OBJECT_NAME => \GiftFlow\Vendor\Stripe\ApplicationFeeRefund::class,
            \GiftFlow\Vendor\Stripe\Apps\Secret::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Apps\Secret::class,
            \GiftFlow\Vendor\Stripe\Balance::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Balance::class,
            \GiftFlow\Vendor\Stripe\BalanceSettings::OBJECT_NAME => \GiftFlow\Vendor\Stripe\BalanceSettings::class,
            \GiftFlow\Vendor\Stripe\BalanceTransaction::OBJECT_NAME => \GiftFlow\Vendor\Stripe\BalanceTransaction::class,
            \GiftFlow\Vendor\Stripe\BankAccount::OBJECT_NAME => \GiftFlow\Vendor\Stripe\BankAccount::class,
            \GiftFlow\Vendor\Stripe\Billing\Alert::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Billing\Alert::class,
            \GiftFlow\Vendor\Stripe\Billing\AlertTriggered::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Billing\AlertTriggered::class,
            \GiftFlow\Vendor\Stripe\Billing\CreditBalanceSummary::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Billing\CreditBalanceSummary::class,
            \GiftFlow\Vendor\Stripe\Billing\CreditBalanceTransaction::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Billing\CreditBalanceTransaction::class,
            \GiftFlow\Vendor\Stripe\Billing\CreditGrant::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Billing\CreditGrant::class,
            \GiftFlow\Vendor\Stripe\Billing\Meter::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Billing\Meter::class,
            \GiftFlow\Vendor\Stripe\Billing\MeterEvent::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Billing\MeterEvent::class,
            \GiftFlow\Vendor\Stripe\Billing\MeterEventAdjustment::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Billing\MeterEventAdjustment::class,
            \GiftFlow\Vendor\Stripe\Billing\MeterEventSummary::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Billing\MeterEventSummary::class,
            \GiftFlow\Vendor\Stripe\BillingPortal\Configuration::OBJECT_NAME => \GiftFlow\Vendor\Stripe\BillingPortal\Configuration::class,
            \GiftFlow\Vendor\Stripe\BillingPortal\Session::OBJECT_NAME => \GiftFlow\Vendor\Stripe\BillingPortal\Session::class,
            \GiftFlow\Vendor\Stripe\Capability::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Capability::class,
            \GiftFlow\Vendor\Stripe\Card::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Card::class,
            \GiftFlow\Vendor\Stripe\CashBalance::OBJECT_NAME => \GiftFlow\Vendor\Stripe\CashBalance::class,
            \GiftFlow\Vendor\Stripe\Charge::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Charge::class,
            \GiftFlow\Vendor\Stripe\Checkout\Session::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Checkout\Session::class,
            \GiftFlow\Vendor\Stripe\Climate\Order::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Climate\Order::class,
            \GiftFlow\Vendor\Stripe\Climate\Product::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Climate\Product::class,
            \GiftFlow\Vendor\Stripe\Climate\Supplier::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Climate\Supplier::class,
            \GiftFlow\Vendor\Stripe\ConfirmationToken::OBJECT_NAME => \GiftFlow\Vendor\Stripe\ConfirmationToken::class,
            \GiftFlow\Vendor\Stripe\ConnectCollectionTransfer::OBJECT_NAME => \GiftFlow\Vendor\Stripe\ConnectCollectionTransfer::class,
            \GiftFlow\Vendor\Stripe\CountrySpec::OBJECT_NAME => \GiftFlow\Vendor\Stripe\CountrySpec::class,
            \GiftFlow\Vendor\Stripe\Coupon::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Coupon::class,
            \GiftFlow\Vendor\Stripe\CreditNote::OBJECT_NAME => \GiftFlow\Vendor\Stripe\CreditNote::class,
            \GiftFlow\Vendor\Stripe\CreditNoteLineItem::OBJECT_NAME => \GiftFlow\Vendor\Stripe\CreditNoteLineItem::class,
            \GiftFlow\Vendor\Stripe\Customer::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Customer::class,
            \GiftFlow\Vendor\Stripe\CustomerBalanceTransaction::OBJECT_NAME => \GiftFlow\Vendor\Stripe\CustomerBalanceTransaction::class,
            \GiftFlow\Vendor\Stripe\CustomerCashBalanceTransaction::OBJECT_NAME => \GiftFlow\Vendor\Stripe\CustomerCashBalanceTransaction::class,
            \GiftFlow\Vendor\Stripe\CustomerSession::OBJECT_NAME => \GiftFlow\Vendor\Stripe\CustomerSession::class,
            \GiftFlow\Vendor\Stripe\Discount::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Discount::class,
            \GiftFlow\Vendor\Stripe\Dispute::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Dispute::class,
            \GiftFlow\Vendor\Stripe\Entitlements\ActiveEntitlement::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Entitlements\ActiveEntitlement::class,
            \GiftFlow\Vendor\Stripe\Entitlements\ActiveEntitlementSummary::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Entitlements\ActiveEntitlementSummary::class,
            \GiftFlow\Vendor\Stripe\Entitlements\Feature::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Entitlements\Feature::class,
            \GiftFlow\Vendor\Stripe\EphemeralKey::OBJECT_NAME => \GiftFlow\Vendor\Stripe\EphemeralKey::class,
            \GiftFlow\Vendor\Stripe\Event::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Event::class,
            \GiftFlow\Vendor\Stripe\ExchangeRate::OBJECT_NAME => \GiftFlow\Vendor\Stripe\ExchangeRate::class,
            \GiftFlow\Vendor\Stripe\File::OBJECT_NAME => \GiftFlow\Vendor\Stripe\File::class,
            \GiftFlow\Vendor\Stripe\FileLink::OBJECT_NAME => \GiftFlow\Vendor\Stripe\FileLink::class,
            \GiftFlow\Vendor\Stripe\FinancialConnections\Account::OBJECT_NAME => \GiftFlow\Vendor\Stripe\FinancialConnections\Account::class,
            \GiftFlow\Vendor\Stripe\FinancialConnections\AccountOwner::OBJECT_NAME => \GiftFlow\Vendor\Stripe\FinancialConnections\AccountOwner::class,
            \GiftFlow\Vendor\Stripe\FinancialConnections\AccountOwnership::OBJECT_NAME => \GiftFlow\Vendor\Stripe\FinancialConnections\AccountOwnership::class,
            \GiftFlow\Vendor\Stripe\FinancialConnections\Session::OBJECT_NAME => \GiftFlow\Vendor\Stripe\FinancialConnections\Session::class,
            \GiftFlow\Vendor\Stripe\FinancialConnections\Transaction::OBJECT_NAME => \GiftFlow\Vendor\Stripe\FinancialConnections\Transaction::class,
            \GiftFlow\Vendor\Stripe\Forwarding\Request::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Forwarding\Request::class,
            \GiftFlow\Vendor\Stripe\FundingInstructions::OBJECT_NAME => \GiftFlow\Vendor\Stripe\FundingInstructions::class,
            \GiftFlow\Vendor\Stripe\Identity\VerificationReport::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Identity\VerificationReport::class,
            \GiftFlow\Vendor\Stripe\Identity\VerificationSession::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Identity\VerificationSession::class,
            \GiftFlow\Vendor\Stripe\Invoice::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Invoice::class,
            \GiftFlow\Vendor\Stripe\InvoiceItem::OBJECT_NAME => \GiftFlow\Vendor\Stripe\InvoiceItem::class,
            \GiftFlow\Vendor\Stripe\InvoiceLineItem::OBJECT_NAME => \GiftFlow\Vendor\Stripe\InvoiceLineItem::class,
            \GiftFlow\Vendor\Stripe\InvoicePayment::OBJECT_NAME => \GiftFlow\Vendor\Stripe\InvoicePayment::class,
            \GiftFlow\Vendor\Stripe\InvoiceRenderingTemplate::OBJECT_NAME => \GiftFlow\Vendor\Stripe\InvoiceRenderingTemplate::class,
            \GiftFlow\Vendor\Stripe\Issuing\Authorization::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Issuing\Authorization::class,
            \GiftFlow\Vendor\Stripe\Issuing\Card::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Issuing\Card::class,
            \GiftFlow\Vendor\Stripe\Issuing\Cardholder::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Issuing\Cardholder::class,
            \GiftFlow\Vendor\Stripe\Issuing\Dispute::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Issuing\Dispute::class,
            \GiftFlow\Vendor\Stripe\Issuing\PersonalizationDesign::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Issuing\PersonalizationDesign::class,
            \GiftFlow\Vendor\Stripe\Issuing\PhysicalBundle::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Issuing\PhysicalBundle::class,
            \GiftFlow\Vendor\Stripe\Issuing\Token::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Issuing\Token::class,
            \GiftFlow\Vendor\Stripe\Issuing\Transaction::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Issuing\Transaction::class,
            \GiftFlow\Vendor\Stripe\LineItem::OBJECT_NAME => \GiftFlow\Vendor\Stripe\LineItem::class,
            \GiftFlow\Vendor\Stripe\LoginLink::OBJECT_NAME => \GiftFlow\Vendor\Stripe\LoginLink::class,
            \GiftFlow\Vendor\Stripe\Mandate::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Mandate::class,
            \GiftFlow\Vendor\Stripe\PaymentAttemptRecord::OBJECT_NAME => \GiftFlow\Vendor\Stripe\PaymentAttemptRecord::class,
            \GiftFlow\Vendor\Stripe\PaymentIntent::OBJECT_NAME => \GiftFlow\Vendor\Stripe\PaymentIntent::class,
            \GiftFlow\Vendor\Stripe\PaymentIntentAmountDetailsLineItem::OBJECT_NAME => \GiftFlow\Vendor\Stripe\PaymentIntentAmountDetailsLineItem::class,
            \GiftFlow\Vendor\Stripe\PaymentLink::OBJECT_NAME => \GiftFlow\Vendor\Stripe\PaymentLink::class,
            \GiftFlow\Vendor\Stripe\PaymentMethod::OBJECT_NAME => \GiftFlow\Vendor\Stripe\PaymentMethod::class,
            \GiftFlow\Vendor\Stripe\PaymentMethodConfiguration::OBJECT_NAME => \GiftFlow\Vendor\Stripe\PaymentMethodConfiguration::class,
            \GiftFlow\Vendor\Stripe\PaymentMethodDomain::OBJECT_NAME => \GiftFlow\Vendor\Stripe\PaymentMethodDomain::class,
            \GiftFlow\Vendor\Stripe\PaymentRecord::OBJECT_NAME => \GiftFlow\Vendor\Stripe\PaymentRecord::class,
            \GiftFlow\Vendor\Stripe\Payout::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Payout::class,
            \GiftFlow\Vendor\Stripe\Person::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Person::class,
            \GiftFlow\Vendor\Stripe\Plan::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Plan::class,
            \GiftFlow\Vendor\Stripe\Price::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Price::class,
            \GiftFlow\Vendor\Stripe\Product::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Product::class,
            \GiftFlow\Vendor\Stripe\ProductFeature::OBJECT_NAME => \GiftFlow\Vendor\Stripe\ProductFeature::class,
            \GiftFlow\Vendor\Stripe\PromotionCode::OBJECT_NAME => \GiftFlow\Vendor\Stripe\PromotionCode::class,
            \GiftFlow\Vendor\Stripe\Quote::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Quote::class,
            \GiftFlow\Vendor\Stripe\Radar\EarlyFraudWarning::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Radar\EarlyFraudWarning::class,
            \GiftFlow\Vendor\Stripe\Radar\PaymentEvaluation::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Radar\PaymentEvaluation::class,
            \GiftFlow\Vendor\Stripe\Radar\ValueList::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Radar\ValueList::class,
            \GiftFlow\Vendor\Stripe\Radar\ValueListItem::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Radar\ValueListItem::class,
            \GiftFlow\Vendor\Stripe\Refund::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Refund::class,
            \GiftFlow\Vendor\Stripe\Reporting\ReportRun::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Reporting\ReportRun::class,
            \GiftFlow\Vendor\Stripe\Reporting\ReportType::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Reporting\ReportType::class,
            \GiftFlow\Vendor\Stripe\Reserve\Hold::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Reserve\Hold::class,
            \GiftFlow\Vendor\Stripe\Reserve\Plan::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Reserve\Plan::class,
            \GiftFlow\Vendor\Stripe\Reserve\Release::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Reserve\Release::class,
            \GiftFlow\Vendor\Stripe\ReserveTransaction::OBJECT_NAME => \GiftFlow\Vendor\Stripe\ReserveTransaction::class,
            \GiftFlow\Vendor\Stripe\Review::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Review::class,
            \GiftFlow\Vendor\Stripe\SetupAttempt::OBJECT_NAME => \GiftFlow\Vendor\Stripe\SetupAttempt::class,
            \GiftFlow\Vendor\Stripe\SetupIntent::OBJECT_NAME => \GiftFlow\Vendor\Stripe\SetupIntent::class,
            \GiftFlow\Vendor\Stripe\ShippingRate::OBJECT_NAME => \GiftFlow\Vendor\Stripe\ShippingRate::class,
            \GiftFlow\Vendor\Stripe\Sigma\ScheduledQueryRun::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Sigma\ScheduledQueryRun::class,
            \GiftFlow\Vendor\Stripe\Source::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Source::class,
            \GiftFlow\Vendor\Stripe\SourceMandateNotification::OBJECT_NAME => \GiftFlow\Vendor\Stripe\SourceMandateNotification::class,
            \GiftFlow\Vendor\Stripe\SourceTransaction::OBJECT_NAME => \GiftFlow\Vendor\Stripe\SourceTransaction::class,
            \GiftFlow\Vendor\Stripe\Subscription::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Subscription::class,
            \GiftFlow\Vendor\Stripe\SubscriptionItem::OBJECT_NAME => \GiftFlow\Vendor\Stripe\SubscriptionItem::class,
            \GiftFlow\Vendor\Stripe\SubscriptionSchedule::OBJECT_NAME => \GiftFlow\Vendor\Stripe\SubscriptionSchedule::class,
            \GiftFlow\Vendor\Stripe\Tax\Association::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Tax\Association::class,
            \GiftFlow\Vendor\Stripe\Tax\Calculation::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Tax\Calculation::class,
            \GiftFlow\Vendor\Stripe\Tax\CalculationLineItem::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Tax\CalculationLineItem::class,
            \GiftFlow\Vendor\Stripe\Tax\Registration::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Tax\Registration::class,
            \GiftFlow\Vendor\Stripe\Tax\Settings::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Tax\Settings::class,
            \GiftFlow\Vendor\Stripe\Tax\Transaction::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Tax\Transaction::class,
            \GiftFlow\Vendor\Stripe\Tax\TransactionLineItem::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Tax\TransactionLineItem::class,
            \GiftFlow\Vendor\Stripe\TaxCode::OBJECT_NAME => \GiftFlow\Vendor\Stripe\TaxCode::class,
            \GiftFlow\Vendor\Stripe\TaxDeductedAtSource::OBJECT_NAME => \GiftFlow\Vendor\Stripe\TaxDeductedAtSource::class,
            \GiftFlow\Vendor\Stripe\TaxId::OBJECT_NAME => \GiftFlow\Vendor\Stripe\TaxId::class,
            \GiftFlow\Vendor\Stripe\TaxRate::OBJECT_NAME => \GiftFlow\Vendor\Stripe\TaxRate::class,
            \GiftFlow\Vendor\Stripe\Terminal\Configuration::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Terminal\Configuration::class,
            \GiftFlow\Vendor\Stripe\Terminal\ConnectionToken::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Terminal\ConnectionToken::class,
            \GiftFlow\Vendor\Stripe\Terminal\Location::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Terminal\Location::class,
            \GiftFlow\Vendor\Stripe\Terminal\OnboardingLink::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Terminal\OnboardingLink::class,
            \GiftFlow\Vendor\Stripe\Terminal\Reader::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Terminal\Reader::class,
            \GiftFlow\Vendor\Stripe\TestHelpers\TestClock::OBJECT_NAME => \GiftFlow\Vendor\Stripe\TestHelpers\TestClock::class,
            \GiftFlow\Vendor\Stripe\Token::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Token::class,
            \GiftFlow\Vendor\Stripe\Topup::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Topup::class,
            \GiftFlow\Vendor\Stripe\Transfer::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Transfer::class,
            \GiftFlow\Vendor\Stripe\TransferReversal::OBJECT_NAME => \GiftFlow\Vendor\Stripe\TransferReversal::class,
            \GiftFlow\Vendor\Stripe\Treasury\CreditReversal::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Treasury\CreditReversal::class,
            \GiftFlow\Vendor\Stripe\Treasury\DebitReversal::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Treasury\DebitReversal::class,
            \GiftFlow\Vendor\Stripe\Treasury\FinancialAccount::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Treasury\FinancialAccount::class,
            \GiftFlow\Vendor\Stripe\Treasury\FinancialAccountFeatures::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Treasury\FinancialAccountFeatures::class,
            \GiftFlow\Vendor\Stripe\Treasury\InboundTransfer::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Treasury\InboundTransfer::class,
            \GiftFlow\Vendor\Stripe\Treasury\OutboundPayment::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Treasury\OutboundPayment::class,
            \GiftFlow\Vendor\Stripe\Treasury\OutboundTransfer::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Treasury\OutboundTransfer::class,
            \GiftFlow\Vendor\Stripe\Treasury\ReceivedCredit::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Treasury\ReceivedCredit::class,
            \GiftFlow\Vendor\Stripe\Treasury\ReceivedDebit::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Treasury\ReceivedDebit::class,
            \GiftFlow\Vendor\Stripe\Treasury\Transaction::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Treasury\Transaction::class,
            \GiftFlow\Vendor\Stripe\Treasury\TransactionEntry::OBJECT_NAME => \GiftFlow\Vendor\Stripe\Treasury\TransactionEntry::class,
            \GiftFlow\Vendor\Stripe\WebhookEndpoint::OBJECT_NAME => \GiftFlow\Vendor\Stripe\WebhookEndpoint::class,
            // object classes: The end of the section generated from our OpenAPI spec
        ];

    /**
     * @var array Mapping from v2 object types to resource classes
     */
    const v2Mapping = [
        // v2 object classes: The beginning of the section generated from our OpenAPI spec
        \GiftFlow\Vendor\Stripe\V2\Billing\MeterEvent::OBJECT_NAME => \GiftFlow\Vendor\Stripe\V2\Billing\MeterEvent::class,
        \GiftFlow\Vendor\Stripe\V2\Billing\MeterEventAdjustment::OBJECT_NAME => \GiftFlow\Vendor\Stripe\V2\Billing\MeterEventAdjustment::class,
        \GiftFlow\Vendor\Stripe\V2\Billing\MeterEventSession::OBJECT_NAME => \GiftFlow\Vendor\Stripe\V2\Billing\MeterEventSession::class,
        \GiftFlow\Vendor\Stripe\V2\Core\Account::OBJECT_NAME => \GiftFlow\Vendor\Stripe\V2\Core\Account::class,
        \GiftFlow\Vendor\Stripe\V2\Core\AccountLink::OBJECT_NAME => \GiftFlow\Vendor\Stripe\V2\Core\AccountLink::class,
        \GiftFlow\Vendor\Stripe\V2\Core\AccountPerson::OBJECT_NAME => \GiftFlow\Vendor\Stripe\V2\Core\AccountPerson::class,
        \GiftFlow\Vendor\Stripe\V2\Core\AccountPersonToken::OBJECT_NAME => \GiftFlow\Vendor\Stripe\V2\Core\AccountPersonToken::class,
        \GiftFlow\Vendor\Stripe\V2\Core\AccountToken::OBJECT_NAME => \GiftFlow\Vendor\Stripe\V2\Core\AccountToken::class,
        \GiftFlow\Vendor\Stripe\V2\Core\Event::OBJECT_NAME => \GiftFlow\Vendor\Stripe\V2\Core\Event::class,
        \GiftFlow\Vendor\Stripe\V2\Core\EventDestination::OBJECT_NAME => \GiftFlow\Vendor\Stripe\V2\Core\EventDestination::class,
        // v2 object classes: The end of the section generated from our OpenAPI spec
    ];
}
