name: Build & Release Plugin

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Install npm dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Build vendor dependencies
        run: composer run build

      - name: Build package
        run: npm run build:package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.MY_GH_TOKEN }}
          files: giftflow.zip
          generate_release_notes: true
